### ISSUE TITLE
consider `loadlibrary`

### ISSUE THREAD

**Issue by nwh** [smitec/rustlab#1]
Hello! I saw your very nice post on connecting Rust and Matlab.  In my PhD, I also wrote a lot of Matlab code.  I ended up finding it sometimes better to use Matlab's `loadlibrary` facility as opposed to `mex`.  I am mentioning this here, because most Matlab users I talk with only know of `mex`.  

http://www.mathworks.com/help/matlab/using-c-shared-library-functions-in-matlab-.html

I maintain a Matlab interface to a Fortran package called LUSOL which demonstrates the use of `loadlibrary`:  https://github.com/nwh/lusol

This is where the shared object is loaded: https://github.com/nwh/lusol/blob/master/matlab/lusol_obj.m#L238

This is a call to the main factorization routine:
https://github.com/nwh/lusol/blob/master/matlab/lusol_obj.m#L750

One benefit of this is that you can allocate memory in Matlab and have calls to the shared object modify that memory in place rather then copying data.  On the downside, there is quite a bit of Matlab code to make the interface nice for the user.

**Comment by smitec** [comment]
thanks @nwh I have updated the project to show both methods. I too hadn't seen the `loadlibrary` function until I posted this. I think it will be a big help when looking at writing libraries with more than one function in them. It saves me having to write the `mexFunction` glue in C
